# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0
#Preparar SonarCloud
- task: SonarCloudPrepare@2
  inputs:
    displayname: "Preparar SonarCloud"
    SonarCloud: 'SonarCloud'
    organization: '@omarnoriega'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=omarnoriega_devsecOps-workshop-continuous-delivery
      sonar.projectName=devsecOps-workshop-continuous-delivery

#Compilación con Maven
- task: Maven@3
  inputs:
    displayName: "Compilar (Build) con Maven & Ejecutar análisis con SonarQube"
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    jdkArchitectureOption: 'x64'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    isJacocoCoverageReportXML: true
    sqMavenPluginVersionChoice: 'latest'
    goals: 'package'

- task: PublishTestResults@2
  inputs:
    displayName: "Publicar Resultados de Test"
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'Resultados Testing'

- task: SonarCloudAnalyze@2
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@2
  inputs:
    displayname: "Publicar Resultados en SonarCloud"
    pollingTimeoutSec: '300'
    
- task: Docker@2
  inputs:
    displayName: "Build Docker Image"
    containerRegistry: 'Service-Connection-Docker'
    repository: 'noriegadocker/kyndryl-workshop-ci'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      
- task: kubectlapply@3
  inputs:
    k8sService: 'Service-Conn-AKS'
    yamlfile: '$(Pipeline.Workspace)/k8s/deployment.yaml'